### ISSUE TITLE
Paper Zotero database: search / filter by attributes

### ISSUE THREAD

**Issue by srjimenez** [BlueBrain/neurocurator#20]
Please enable a search capability in the  "Paper Zotero database".
It takes a long time to scroll the list of papers.

**Comment by pafonta** [comment]
In the meantime, records can be sorted by each column except the 'Annotations' one (see #18).

**Comment by pafonta** [comment]
Fixed in [v0.4.0](https://github.com/BlueBrain/neurocurator/tree/v0.4.0).
