### ISSUE TITLE
how to install and use ?

### ISSUE THREAD

**Issue by awakenting** [BlueBrain/neurocurator#4]
Hello,
I find the idea of this project great but how can I actually use it ?
I think it would be very helpful if there was an "Install" and a "Getting started" section in the readme because right now I have no idea how to use it.

**Comment by christian-oreilly** [comment]
Hi,

Thank you for your feedback. You are definitely right about the need for more documentation to help users get started with using these tools. We are currently lacking the man power to progress at a good pace but we are in process of recruiting someone who will be able to take on development, documentation, and user support for these tools. 

We will try to address these issues as soon as possible. Best wishes,

Christian

**Comment by awakenting** [comment]
Thanks for the quick answer!
If you could give me some quick hints I could already try to work through it myself and then write up a first draft of how to use it. I'm quite familiar with python so you probably just need to tell me where to look at.

Otherwise I wish you good luck with the recruiting and further work. I'm looking forward to using this.

Best,
Andrej

**Comment by christian-oreilly** [comment]
Hi,

The very short answer is that you can just run "python3 main.py" to launch
the application (this suppose that it has been installed properly). I
copied in the project wiki (https://github.com/BlueBrain/neurocurator/wiki)
some documentation that I wrote a while ago. Beware thought: there are many
things in this copied documentation that need to be updated but I hope it
might nevertheless guide you in the right direction (particularly the
installation page).

Best,

Christian

2017-04-21 11:50 GMT+02:00 awakenting <notifications@github.com>:

**Comment by LaviniaUscatescu** [comment]
Hi, Christian,

When I try to run the setup file, I get the following error:

C:\Program Files (x86)\PsychoPy2\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

Any ideas?

Thanks,
Lavinia

**Comment by christian-oreilly** [comment]
For the warning: Is your pip install up-to-date? You can run: pip install
pip --upgrade

For the error: It looks like you ran "python setup.py" and it complains
that you should specify a command (like "install"). Try "python setup.py
install".

By the way, I never tried to install it on Windows. let me know how it
goes. If you run in too much problems, I'll try it also from my side.

Best,

Christian

2017-04-27 12:29 GMT+02:00 LaviniaUscatescu <notifications@github.com>:

**Comment by pafonta** [comment]
Hi @LaviniaUscatescu,
Hi @awakenting,

If you have a Mac or a Debian-based system, I have just created standalone executables you could use. See the [new section](https://github.com/BlueBrain/neurocurator/blob/master/README.md#installation) for further information. Please note that this is **experimental** at the moment. Other installation possibilities will come in the following months.

Best,
Pierre-Alexandre

**Comment by pafonta** [comment]
For macOS and Ubuntu (Debian-based distributions), see the new [Getting Started](https://github.com/BlueBrain/neurocurator#getting-started).

For Windows (unsupported), see #53.

**Comment by pafonta** [comment]
The new installation procedure coming with v04.1 makes easier to install on macOS, GNU/Linux and Windows and to launch NeuroCurator after installation.
https://github.com/BlueBrain/neurocurator/blob/v0.4.1/README.md#getting-started
