### ISSUE TITLE
[Projects] Don't preset the Zotero API key

### ISSUE THREAD

**Issue by pafonta** [BlueBrain/neurocurator#51]

**Comment by pafonta** [comment]
To keep the demonstration purpose:
- Create a Zotero library with the 10 most annotated CC-BY 4.0 papers.
- Create a GitHub repository with the annotations for these papers.
- Configure NeuroCurator to access this repository and this library by default.

**Comment by christian-oreilly** [comment]
Pending for a more complete resolution of this issue, the Zotero and GitHub preset values in the configuration dialog have been removed (commit cc4269d4843bc64d15f1a8ebf9be6d7abb2d996d ).

**Comment by pafonta** [comment]
As the roadmap has more and more tasks, I created an issue specific for the creation of the demo project - https://github.com/BlueBrain/neurocurator/issues/97 - and close this one as the work has been done.
