### ISSUE TITLE
[Annotations] Tags at the level of a reference instead of an annotation

### ISSUE THREAD

**Issue by pafonta** [BlueBrain/neurocurator#68]
**Currently**
Tags are at the level of an annotation.
The annotations for a reference share - almost, _to be confirmed_ [1] - the same tags.

**Issues**
Add manually the same tags for all new annotations for a given reference.
Data duplication.

**Solution**
Move the tags from the annotation level to the reference one.
Or, depending of [1], introduce tags at the reference level.

**Comment by pafonta** [comment]
@christian-oreilly for review.

**Comment by christian-oreilly** [comment]
From the user point-of-view, their is a functionality to mimic the effect of a "reference-level tag". This mechanism has been documented in https://github.com/BlueBrain/neurocurator/wiki/Using-the-Neurocurator:-Overview as making a tag "persistent for the paper". There are currently no mechanisms to add information at the paper level, everything being either at the annotation or the parameter level. Adding support for information at the paper level might have some advantages (e.g., reducing data redundancy) but also add complexity (e.g., some information at the paper level such as the species may not apply to a specific annotations concerning another species in this paper). Also, it means that, programmatically, the annotation object is not self-contained and may require to go back to the level of the paper to complete the annotation information.

**Comment by pafonta** [comment]
Tagged _won't fix_ and closed because:

> their is a functionality to mimic the effect of a "reference-level tag"

and

> some information at the paper level such as the species may not apply to a specific annotations concerning another species in this paper
