### ISSUE TITLE
[References] I've selected the wrong PDF; how do I replace it?

### ISSUE THREAD

**Issue by davidcsterratt** [BlueBrain/neurocurator#78]
1. Create a ref in a Zotero library
2. In neurocurator, "Zotero"->"Refresh library"
3. I'm asked to add a PDF
4. I'm not used to the Qt interface (running in a MATE desktop), so I double-click instead of single-click in the file dialog and select the wrong PDF from my filesystem.

How do I get rid of the wrong PDF and select the correct one?

**Comment by pafonta** [comment]
Is the DOI `10.1038/nn893`?

**Comment by davidcsterratt** [comment]
The correct DOI should be 10.1038/nn.2746 . The incorrect DOI (i.e. the DOI of the PDF I've uploaded) is indeed 10.1038/nn893.

**Comment by pafonta** [comment]
If you close NeuroCurator and then open it again, you should now be able to attach the correct PDF.

**Comment by pafonta** [comment]
@davidcsterratt Can we close the issue?
